### PR TITLE
Fix package name normalization as per PEP-503 spec

### PR DESCRIPTION
**Pull request by aiman-alsari**
Replaces all dots and underscores with dashes, and lowercases.

### CODE REVIEW

**Comment by saurfangg** [comment]
Any chance of getting this merged?

**Comment by wolever** [comment]
Ahh! I'm so sorry for the delay. Yep, I'll be reviewing + merging this by EOD today! Thank you for the patience!

**Comment by wolever** [comment]
Okay! Took a tad longer than expected, but I've just pushed 0.7.0rc1, which should correctly normalize package names.

Would you be able to install it:

    pip install pip2pi==0.7.0rc1

And let me know if it works?

Thanks!

**Comment by aiman-alsari** [comment]
@wolever - tested this and it works great, thanks.

**Pull request closed without merging**
